name: Auto Bot Runner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build --build-arg MAXMIND_LICENSE_KEY=$MAXMIND_LICENSE_KEY -t bot .
        
    - name: Run container
      run: |
        docker run -d --name running-bot bot
        
    - name: Monitor logs
      run: |
        docker logs -f running-bot
